name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar JMeter
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xzf apache-jmeter-5.5.tgz
          sudo mv apache-jmeter-5.5 /opt/jmeter
          echo "/opt/jmeter/bin" >> $GITHUB_ENV

      # Baixar e instalar o JUnitReporter plugin
      - name: Install JUnitReporter plugin
        run: |
          mkdir -p /opt/jmeter/lib/ext
          wget https://repo1.maven.org/maven2/nz/co/breakpoint/jmeter/junit-reporter/1.3/junit-reporter-1.3.jar -P /opt/jmeter/lib/ext

      # Criar diretório para relatórios
      - name: Create reports directory
        run: mkdir -p reports/html

      # Executar JMeter
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        if: always()
        with:
          test-plan-path: CompraPassagem90thPercentil.jmx
          results-file: result.jtl
          args: ""
