name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create reports directory
      - name: Create reports directory
        run: mkdir -p reports

      # Run JMeter Tests plugins
      - name: Run JMeter Tests plugins
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with: 
          testFilePath: teste/CompraPassagem90thPercentil.jmx
          outputReportsFolder: reports/TEST.xml  # Ajuste para o formato correto, caso necessário
          args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"
          plugins: "tilln-junit"

      # List report files
      - name: List report files
        run: |
          ls -l reports/

      # JUnit Report Action
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v5.0.0-a03
        if: success()  # Executa somente se a etapa anterior foi bem-sucedida
        with: 
          token: ${{ github.token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: reports/TEST.xml
