name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Execute os testes JMeter
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        if: always()
        with:
          testFilePath: teste/CompraPassagem90thPercentil.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"
          plugins: "tilln-junit"

      # Fazer upload dos relatórios como artefatos
      - name: Upload JMeter reports
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-reports
          path: reports/
