name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JMeter and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xzf apache-jmeter-5.5.tgz
          sudo mv apache-jmeter-5.5 /opt/jmeter
          echo "/opt/jmeter/bin" >> $GITHUB_ENV

      - name: Install JMeter Plugins Manager
        run: |
          wget https://jmeter-plugins.org/files/packages/JMeterPlugins-Manager-1.4.0.jar -P /opt/jmeter/lib/ext
          /opt/jmeter/bin/jmeter -n -t /opt/jmeter/lib/ext/JMeterPlugins-Manager-1.4.0.jar

      - name: Install Required Plugins
        run: |
          /opt/jmeter/bin/jmeter -n -Jpluginsmanager.autodownload=true -Jpluginsmanager.install=JUnitReporter

      - name: Create reports directory
        run: mkdir -p reports/html

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        if: always()
        with:
          test-plan-path: CompraPassagem90thPercentil.jmx
          results-file: result.jtl
          args: ""
