name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Run JMeter Tests plugins
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        if: always()
        with: 
              testFilePath: CompraPassagem90thPercentil.jmx
              outputReportsFolder: report/TEST.xml
              args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"
              plugins: "tilln-junit"


      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v5.0.0-a03
        if: always()
        with: 
            token:  ${{ github.token }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            report_paths: report/TEST.xml
    
