name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create reports directory
      - name: Create reports directory
        run: mkdir -p reports
               
                
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.2
        if: always()
        with:
            test-plan-path: CompraPassagem90thPercentil.jmx
            results-file: reports/result.jtl
            args: ""
