# Workflow to run JMeter tests and upload results

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir reports

      # Run JMeter test and generate the result file
      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          test-plan-path: CompraPassagem90thPercentil.jmx
          args: "-e -o ./reports/html"  # Removed -l to avoid duplicate option

      # Upload JMeter results (look for the JTL file in a default or known location)
      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          name: jmeter-results
          path: ./CompraPassagem90thPercentil.jtl  # Explicitly checking the JTL file based on test plan name
          if-no-files-found: error

      # Upload HTML reports generated by JMeter
      - name: Upload JMeter HTML Reports
        uses: actions/upload-artifact@v3
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          name: jmeter-html-reports
          path: reports
          if-no-files-found: error
      # List files in the working directory
      - name: List files after JMeter test
        run: ls -R
