name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Run JMeter Tests plugins
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        if: always()
        with: 
              testFilePath: CompraPassagem90thPercentil.jmx
              outputReportsFolder: reports/
              args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"
              plugins: "tilln-junit"



