name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do reposit贸rio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Criar diret贸rio para relat贸rios
      - name: Create reports directory
        run: mkdir -p reports/html

      # Executar testes JMeter
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: CompraPassagem90thPercentil.jmx
          args: "-e -o ./reports/html/"

      # Fazer upload dos resultados JTL
      - name: Upload JTL Results
        uses: actions/upload-artifact@v3
        if: always()  # Fazer upload independente do sucesso ou falha
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error

      # Fazer upload dos relat贸rios HTML
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        if: always()  # Fazer upload independente do sucesso ou falha
        with:
          name: jmeter-html-reports
          path: reports/html/**  # Captura todos os arquivos HTML gerados
          if-no-files-found: error
